Features/run as account
slapointe/Azure-Automation-Scheduled-VM-Shutdown pull request #1
Opened 2017-10-15 20:03 UTC by skaue

Removed dependency to Credentials and made the script run using RunAsAccounts. Adjustments to the code accessing tags.

2017-10-15 20:13 UTC, skaue reviewed
This code removes code from the master branch, rendering it incompatible with the original code.

2018-06-20 16:33 UTC, slapointe commented on Assert-AutoShutdownSchedule.ps1
> +        $resourceList += @(Get-AzureRmResource -ResourceType $_.ResourceType)
Please use ```Get-AzureRmResource -ODataQuery ("`$filter=resourcetype eq '{0}'" -f $_.ResourceType)```. Get-AzureRmResource -ResourceType have compatibility issues over differents versions

2018-06-20 16:52 UTC, slapointe requested changes
Please fix the `Get-AzureRmResource -ResourceType` calls like in the following article: 
https://www.codeisahighway.com/how-to-safely-replace-find-azurermresource-resourcetype-calls-in-azure-powershell-6-x/

2018-08-23 10:43 UTC, skaue commented
Like this? :)

2018-08-25 16:51 UTC, slapointe approved these changes

2018-08-25 16:52 UTC, slapointe commented
Thanks @skaue for your contribution!

2018-08-25 16:55 UTC, merged